// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztwhbnltoepqinxlswjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0d2hibmx0b2VwcWlueGxzd2pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MDg0NjcsImV4cCI6MjA2NzQ4NDQ2N30.ZwRLz7QTE-juAhiLSXU6UTWEShtnzB2z91dxuYZF8zw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});